#!/usr/bin/python3
import argparse
import os
import sys
import getpass

# Confirm that user is running python3
if sys.hexversion < 0x3000000:
    print("Please use python3")
    sys.exit(0)

# Attempt to import cryptography modules
try:
    from cryptography.hazmat.primitives.ciphers import aead
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
    from cryptography.hazmat.backends import default_backend
    from cryptography.exceptions import InvalidTag
except ImportError:
    print("scrypto requires cryptography. Install with: "
          "pip3 install cryptography")
    sys.exit(0)

# CRYPTO MODULES
CIPHERS = {
        'AES-GCM': aead.AESGCM
}
HASHERS = {
        'SHA256': hashes.SHA256(),
}
backend = default_backend()


class CryptoError(Exception):
    """Exception raised for errors related to message decryption"""
    def __init__(self, message):
        self.message = message


class Crypto(object):
    """Handles all cryptographic operations"""
    def __init__(self, cipher, hasher, password, salt=None, nonce=None):
        self.nonce = nonce or self.get_random_bytes(16)
        self.hasher = HASHERS[hasher]
        self.salt = salt or self.get_random_bytes(16)
        self.key = self.derive_key(password)
        self.key_hash = self.hash(self.key)
        self.cipher = CIPHERS[cipher](self.key)

    def get_random_bytes(self, n):
        """Returns n bytes of randomness"""
        return os.urandom(n)

    def constant_time_comparison(self, str1, str2):
        """Compares two strings in constant times to avoid timing attacks"""
        if len(str1) != len(str2):
            raise CryptoError("File is of incorrect format")
        is_equal = True
        for a, b in zip(str1, str2):
            if a != b:
                is_equal = False
        return is_equal

    def verify_password(self, key_hash):
        """Verifies password hash"""
        # Check if password is correct before decryption b/c padding oracles
        if not self.constant_time_comparison(self.key_hash, key_hash):
            raise CryptoError("Key hash comparison failed --> Invalid password"
                              " or file has been tampered with")

    def derive_key(self, password):
        """Runs PBKDF2 with 300000 iterations on provided password"""
        # You'll probably want to change iterations to something
        # smaller.
        # Using SHA256 to avoid https://eprint.iacr.org/2016/273.pdf
        kdf = PBKDF2HMAC(self.hasher,
                         length=32,
                         salt=self.salt,
                         iterations=300000,
                         backend=default_backend()
                         )
        key = kdf.derive(password)
        return key

    def hash(self, msg):
        """Computes the hash of a given msg"""
        hasher = hashes.Hash(self.hasher, backend=default_backend())
        hasher.update(msg)
        return hasher.finalize()

    def aes_encrypt(self, plaintext, filename):
        """Encrypts plaintext using specified cipher and provided key"""
        ciphertext = self.cipher.encrypt(self.nonce, plaintext,
                                         bytes(filename, 'utf-8'))
        return ciphertext

    def aes_decrypt(self, ciphertext, filename):
        """Decrypts ciphertext using specified cipher and provided key/nonce"""
        try:
            plaintext = self.cipher.decrypt(self.nonce, ciphertext,
                                            bytes(filename, 'utf-8'))
        except InvalidTag:
            raise CryptoError("Invalid Tag --> File has been tampered with")
        return plaintext


class FileHandler(object):
    """Handles all file i/o"""
    def __init__(self, content, cwd, operation, filename=None):
        self.content = content
        self.cwd = cwd
        self.operation = operation
        self.name = filename

    def write(self):
        with open(self.cwd + '/' + self.name_to_write, 'bw') as f:
            f.write(self.to_write)
        if self.operation == "Encrypt":
            print("File: {} encrypted!".format(self.name))
        else:
            print("File: {} decrypted!".format(self.name))

    def generate_enc_file(self, crypto):
        """Returns all elements concatenated together and tagged correctly"""
        # Forward slashes are banned in filenames so use that as a separator
        self.name_to_write = self.name.split(".")[0] + ".enc"
        # TODO: Consider changing self.name to default bytes?
        self.to_write = (bytes(self.name, 'utf-8') + b"/" + crypto.salt +
                         crypto.key_hash + crypto.nonce + self.content)

    def decode_file(self, password):
        """Parses an encrypted file into the corresponding crypto object"""
        # Extract all components of file
        try:
            self.name_to_write = str(self.content.split(b"/")[0], 'utf-8')
            # TODO: Rename again
            content = self.content.split(b"/")[1]
            salt = content[:16]
            key_hash = content[16:48]
            nonce = content[48:64]
            ciphertext = content[64:]
        except IndexError:
            raise CryptoError("File has been tampered with")

        # Generate crypto object and verify integrity
        crypto = Crypto("AES-GCM", "SHA256", password, salt, nonce)
        crypto.verify_password(key_hash)
        return crypto, ciphertext, self.name_to_write

    def get_files(cwd, filenames, remove):
        """Return a list containing tuples of all filenames and plaintexts"""
        files = []
        for filename in filenames:
            try:
                file = open(cwd + '/' + filename, 'rb')
                # Each element is a tuple of filename and contents
                files.append((filename, file.read()))
                file.close()
            except IOError:
                    print("Given file: " + filename +
                          " does not exist. Skipping")
            # Delete the original file if the option was set by user
            if remove:
                os.remove(cwd + '/' + filename)
        return files


def make_parser():
    """Builds ArgumentParser Object"""
    parser = argparse.ArgumentParser(description='Encrypt files using 128-bit '
                                     'AES')
    parser.add_argument('filenames', nargs='+',
                        help='Files to encrypt/decrypt (Default is encrypt)',
                        type=str)
    parser.add_argument('-d', '--decrypt', required=False,
                        action='store_true',
                        help='Decrypt file')
    parser.add_argument('-r', '--remove', required=False,
                        action='store_true',
                        help='Remove original file')
    return parser


def encryptor(password, cwd, file):
    """Encrypts the given file with the given password"""
    # Create crypto object
    filename, plaintext = file
    crypto = Crypto("AES-GCM", "SHA256", password)

    # Encrypt and write file
    ciphertext = crypto.aes_encrypt(plaintext, filename)
    file_handler = FileHandler(ciphertext, cwd, "Encrypt", filename)
    file_handler.generate_enc_file(crypto)
    file_handler.write()


def decryptor(password, cwd, file):
    """Decrypts the given file with the given password"""
    # Parse file and create crypto object
    filename, enc_file = file
    file_handler = FileHandler(enc_file, cwd, "Decrypt", filename)
    # TODO: rename filename to something that doesn't conflict
    crypto, ciphertext, filename = file_handler.decode_file(password)

    # Decrypt and write file
    plaintext = crypto.aes_decrypt(ciphertext, filename)
    file_handler.to_write = plaintext
    file_handler.write()


if __name__ == "__main__":
    # Get arguments and files
    cwd = os.getcwd()
    args = make_parser().parse_args()
    filenames = args.filenames
    remove = args.remove
    decrypt = args.decrypt
    password = bytes(getpass.getpass(), 'utf-8')
    files = FileHandler.get_files(cwd, filenames, remove)

    # Set modifer functions depending on user-requested action
    if decrypt:
        modifier = decryptor
    else:
        modifier = encryptor

    # Encrypt/decrypt each file
    for file in files:
        modifier(password, cwd, file)
